<?php
/**
 * @category   MW
 * @package    MW_All
 * @version    1.0.0
 * @copyright  Copyright (c) 2012 Mage Whiz. (http://www.magewhiz.com)
 */
?>
<?php if ($this->_section == 'mwall'): ?>
<div id="mwall_extensions_table">
    <table class="form-list">
        <tbody>
            <?php foreach ($this->getExtensions() as $Extension): ?>
        <tr>
            <td><img src="<?php echo $this->getIcon($Extension)->getSource()?>"
                     alt="<?php echo $this->getIcon($Extension)->getTitle()?>"/></td>
            <td><a href="<?php echo $Extension->getFeedInfo()->getUrl()?>"
                   onclick="this.target = '_blank'"><?php echo $Extension->getFeedInfo()->getDisplayName()?></a></td>
            <td><?php echo $Extension->getVersion()?></td>
            <td>
                <a href="http://www.magewhiz.com/mwextensions/<?php echo $Extension->getName()?>/<?php echo $Extension->getVersion()?>/installation_guide.pdf"
                   onclick="this.target = '_blank'"><img
                        src="<?php echo $this->getSkinUrl('mw/all/images/doc.png')?>"/></a></td>
        </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>
<?php if ($this->_section == 'mwextension'): ?>
<div id="mwextension_response">
    <?php echo $this->_getMwExtensionData()->getTextResponse()?>
</div>
<?php endif; ?>

<?php if ($this->_section == 'mwtheme'): ?>
<div id="mwtheme_response">
    <?php echo $this->_getMwThemeData()->getTextResponse()?>
</div>
<?php endif; ?>

<script type="text/javascript">
    _section = '<?php echo $this->_section?>';
</script>