<?php
/**
 * @category   MW
 * @package    MW_All
 * @version    1.0.0
 * @copyright  Copyright (c) 2012 Mage Whiz. (http://www.magewhiz.com)
 */
?>

<div id="mwall_whiz_extensions">
    <table class="form-list">
        <tbody>
        <?php foreach ($this->getExtensions() as $extension): $status = $extension->getActive();?>
        <tr>
            <td><img src="<?php echo $extension->getIcon()->getSrc()?>"
                     alt="<?php echo $extension->getIcon()->getTitle()?>"/></td>
            <td><a href="<?php echo $extension->getExtensionInfo()->getUrl()?>"
                   onclick="this.target = '_blank'"><?php echo $extension->getExtensionInfo()->getDisplayName()?></a>
            </td>
            <td><?php echo $extension->getVersion()?></td>
            <td>
                <a href="http://www.magewhiz.com/mwextensions/<?php echo $extension->getName()?>/<?php echo $extension->getVersion()?>/installation_guide.pdf"
                                   onclick="this.target = '_blank'"><img
                                        src="<?php echo $this->getSkinUrl('mw/all/images/doc.png')?>"/></a></td>
            <td><select class="select" name="modules[<?php echo $extension->getName()?>]" id="<?php echo $extension->getName()?>">
                <option <?php echo  $status?'selected="selected"':'' ?> value="1">Enabled</option>
                <option <?php echo  !$status?'selected="selected"':'' ?> value="0">Disabled</option>
            </select></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>